<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TMI6UL6" failures="0" tests="17" name="studi.co.testScripts.Assignment_Listing" time="15.333" errors="1" timestamp="30 Jul 2021 12:17:43 GMT" skipped="16">
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC06_To_Verify_All_Assignments_are_Represents_With_Due_Date_of_That_Assignment" time="0.000">
    <skipped/>
  </testcase> <!-- TC06_To_Verify_All_Assignments_are_Represents_With_Due_Date_of_That_Assignment -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC12_Once_the_Assignment_is_created__Alert_Notification_of_Success_message_should_be_Displayed" time="0.000">
    <skipped/>
  </testcase> <!-- TC12_Once_the_Assignment_is_created__Alert_Notification_of_Success_message_should_be_Displayed -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC16_To_Verify_the_scrolling_functionality" time="0.000">
    <skipped/>
  </testcase> <!-- TC16_To_Verify_the_scrolling_functionality -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC21_To_Verify_Total_Due_Resources_shown_to_user_In_each_section" time="0.000">
    <skipped/>
  </testcase> <!-- TC21_To_Verify_Total_Due_Resources_shown_to_user_In_each_section -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC02_Verify_intent_creation_module_using_that_User_can_create_test_for_Students" time="0.000">
    <skipped/>
  </testcase> <!-- TC02_Verify_intent_creation_module_using_that_User_can_create_test_for_Students -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC11_after_selecting_topic_new_assignment_is_created_with_label_new" time="0.000">
    <skipped/>
  </testcase> <!-- TC11_after_selecting_topic_new_assignment_is_created_with_label_new -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC08_attachment_icon_will_be_shown_in_case_there_any_attachment_assignment" time="0.000">
    <skipped/>
  </testcase> <!-- TC08_attachment_icon_will_be_shown_in_case_there_any_attachment_assignment -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC23_To_Verify_On_Completed_Assignment_List_actul_Task_Complete_Date_is_Shown" time="0.000">
    <skipped/>
  </testcase> <!-- TC23_To_Verify_On_Completed_Assignment_List_actul_Task_Complete_Date_is_Shown -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC07_To_Verify_If_User_Does_Not_Complete_The_Assignment_On_Certain_Due_Date_Count_Of_Extra_Days_Will_Be_Shown_Above_The_Date" time="0.000">
    <skipped/>
  </testcase> <!-- TC07_To_Verify_If_User_Does_Not_Complete_The_Assignment_On_Certain_Due_Date_Count_Of_Extra_Days_Will_Be_Shown_Above_The_Date -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC03_To_verify_items_of_today_Upcoming_shown_prominently_on_the_listing_page" time="0.000">
    <skipped/>
  </testcase> <!-- TC03_To_verify_items_of_today_Upcoming_shown_prominently_on_the_listing_page -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC04_To_verify_Newly_Created_Assignments_In_Todays_Task_Are_Shown_With_New_Icon" time="0.000">
    <skipped/>
  </testcase> <!-- TC04_To_verify_Newly_Created_Assignments_In_Todays_Task_Are_Shown_With_New_Icon -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC14_To_Verify_when_User_clicks_on_View_completed_link_all_completed_assignments_shown_to_user" time="0.000">
    <skipped/>
  </testcase> <!-- TC14_To_Verify_when_User_clicks_on_View_completed_link_all_completed_assignments_shown_to_user -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC24_To_Verify_that_On_Listing_Page_User_able_to_Create_Task_And_Both_Type_of_Test" time="0.000">
    <skipped/>
  </testcase> <!-- TC24_To_Verify_that_On_Listing_Page_User_able_to_Create_Task_And_Both_Type_of_Test -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="beforeTest" time="15.333">
    <error message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;DESKTOP-TMI6UL6&#039;, ip: &#039;192.168.31.152&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;15.0.2&#039;
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
    at JWProxy.command (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:280:13)
    at runMicrotasks (&lt;anonymous&gt;)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;DESKTOP-TMI6UL6&#039;, ip: &#039;192.168.31.152&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;15.0.2&#039;
Driver info: driver.version: AndroidDriver" type="org.openqa.selenium.SessionNotCreatedException">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-TMI6UL6', ip: '192.168.31.152', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
    at JWProxy.command (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:280:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-TMI6UL6', ip: '192.168.31.152', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:95)
at studi.co.Base.BaseClass.beforeTest(BaseClass.java:338)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 37 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-TMI6UL6', ip: '192.168.31.152', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
    at JWProxy.command (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:280:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
... 42 more
]]>
    </error>
  </testcase> <!-- beforeTest -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC01_Verify_User_Should_Be_Able_To_See_Listing_Of_Today_Upcoming_Completed_Assignments" time="0.000">
    <skipped/>
  </testcase> <!-- TC01_Verify_User_Should_Be_Able_To_See_Listing_Of_Today_Upcoming_Completed_Assignments -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC05_To_Verify_New_Created_Tasks_Icon_Once_User_Exits_The_Current_Screen_And_Comes_Back_New_will_not_be_shown">
    <skipped/>
  </testcase> <!-- TC05_To_Verify_New_Created_Tasks_Icon_Once_User_Exits_The_Current_Screen_And_Comes_Back_New_will_not_be_shown -->
  <testcase classname="studi.co.testScripts.Assignment_Listing" name="TC09_Assignment_wil_be_strikedThrough_if_user_completed_the_assignment_either_by_Mark_as_complete_or_actual_completion">
    <skipped/>
  </testcase> <!-- TC09_Assignment_wil_be_strikedThrough_if_user_completed_the_assignment_either_by_Mark_as_complete_or_actual_completion -->
</testsuite> <!-- studi.co.testScripts.Assignment_Listing -->
