<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TMI6UL6" failures="5" tests="13" name="studi.co.testScripts.AFS_UserStory_63" time="1410.221" errors="0" timestamp="28 Jul 2021 08:12:37 GMT" skipped="0">
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC11_Verify_Save_Note_And_Discard_Button_Enable_After_User_Entering_Note" time="86.794">
    <failure message="The following asserts failed:
	Save note Button clickable without entering Text expected [false] but found [true],
	Discard Button clickable without entering Text expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Save note Button clickable without entering Text expected [false] but found [true],
Discard Button clickable without entering Text expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at studi.co.pageModules.Module_Syllabus_Options.Verify_Save_Note_And_Discard_Button_Enable_After_User_Entering_Note(Module_Syllabus_Options.java:2301)
at studi.co.testScripts.AFS_UserStory_63.TC11_Verify_Save_Note_And_Discard_Button_Enable_After_User_Entering_Note(AFS_UserStory_63.java:88)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- TC11_Verify_Save_Note_And_Discard_Button_Enable_After_User_Entering_Note -->
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC01_Verify_Create_Note_Icon_Should_Be_Visible_In_Video" time="101.847"/>
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC09_Verify_Save_Note_Button_Enable_After_User_Entering_Note" time="107.551">
    <failure message="The following asserts failed:
	Save note Button clickable without entering Text expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Save note Button clickable without entering Text expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at studi.co.pageModules.Module_Syllabus_Options.Verify_Save_Note_Button_Enable_After_User_Entering_Note(Module_Syllabus_Options.java:2115)
at studi.co.testScripts.AFS_UserStory_63.TC09_Verify_Save_Note_Button_Enable_After_User_Entering_Note(AFS_UserStory_63.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- TC09_Verify_Save_Note_Button_Enable_After_User_Entering_Note -->
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC15_Verify_Note_Area_Have_Initial_Message_For_Entering_Text" time="99.882">
    <failure message="The following asserts failed:
	Guidance message not available in Note Text area expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Guidance message not available in Note Text area expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at studi.co.pageModules.Module_Syllabus_Options.Verify_Note_Area_Have_Initial_Message_For_Entering_Text(Module_Syllabus_Options.java:2354)
at studi.co.testScripts.AFS_UserStory_63.TC15_Verify_Note_Area_Have_Initial_Message_For_Entering_Text(AFS_UserStory_63.java:103)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- TC15_Verify_Note_Area_Have_Initial_Message_For_Entering_Text -->
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC10_Verify_Save_Note_And_Discard_Button_Should_Be_Disable_Initially" time="100.511">
    <failure message="The following asserts failed:
	Save note Button clickable without entering Text expected [false] but found [true],
	Discard Button clickable without entering Text expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Save note Button clickable without entering Text expected [false] but found [true],
Discard Button clickable without entering Text expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at studi.co.pageModules.Module_Syllabus_Options.Verify_Save_Note_And_Discard_Button_Should_Be_Disable_Initially(Module_Syllabus_Options.java:2190)
at studi.co.testScripts.AFS_UserStory_63.TC10_Verify_Save_Note_And_Discard_Button_Should_Be_Disable_Initially(AFS_UserStory_63.java:81)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- TC10_Verify_Save_Note_And_Discard_Button_Should_Be_Disable_Initially -->
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC08_Verify_Save_Note_Button_Should_Be_Disable_Initially" time="105.544">
    <failure message="The following asserts failed:
	Save note Button clickable without entering Text expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Save note Button clickable without entering Text expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at studi.co.pageModules.Module_Syllabus_Options.Verify_Save_Note_Button_Should_Be_Disable_Initially(Module_Syllabus_Options.java:2040)
at studi.co.testScripts.AFS_UserStory_63.TC08_Verify_Save_Note_Button_Should_Be_Disable_Initially(AFS_UserStory_63.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- TC08_Verify_Save_Note_Button_Should_Be_Disable_Initially -->
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC02_Verify_Create_Note_Icon_Should_Be_Clickable_In_Video" time="101.345"/>
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC07_Verify_User_Is_Able_To_Enter_Special_Characters_In_Note" time="111.756"/>
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC06_Verify_User_Is_Unable_To_Add_Empty_Note" time="107.700"/>
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC14_Verify_Note_Module_Will_Closed_Without_Warning" time="111.537"/>
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC42_Verify_Warning_Message_Shown_After_Clicking_Discard_In_Notes" time="129.466"/>
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC05_Verify_User_Should_Be_Able_To_Write_Upto_3000_Charcters_In_Note" time="94.593"/>
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC43_Verify_Notes_Will_Be_Saved_Using_Save_Note_Option" time="151.695"/>
</testsuite> <!-- studi.co.testScripts.AFS_UserStory_63 -->
