<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-JHURRHK" failures="5" tests="10" name="studi.co.testScripts.Syllabus_BrowseBook" time="240.289" errors="1" timestamp="13 Aug 2021 19:17:24 GMT" skipped="0">
  <testcase classname="studi.co.testScripts.Syllabus_BrowseBook" name="TC17_To_Verify_User_Can_Navigate_To_Create_Oral_Test_Page" time="13.995"/>
  <testcase classname="studi.co.testScripts.Syllabus_BrowseBook" name="TC15_To_Verify_Practice_Is_Disabled_If_Completed_In_School" time="27.697">
    <failure message="The following asserts failed:
	User is able to start practice which is Completed In School expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
User is able to start practice which is Completed In School expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at studi.co.pageModules.Module_Syllabus_BrowseBook.validate_practice_completedInSchool_functionality(Module_Syllabus_BrowseBook.java:208)
at studi.co.testScripts.Syllabus_BrowseBook.TC15_To_Verify_Practice_Is_Disabled_If_Completed_In_School(Syllabus_BrowseBook.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- TC15_To_Verify_Practice_Is_Disabled_If_Completed_In_School -->
  <testcase classname="studi.co.testScripts.Syllabus_BrowseBook" name="TC18_To_Verify_User_Can_Navigate_To_Create_Oral_Test_Page" time="15.940"/>
  <testcase classname="studi.co.testScripts.Syllabus_BrowseBook" name="TC16_To_Verify_User_Can_Navigate_To_Create_Oral_Test_Page" time="18.547"/>
  <testcase classname="studi.co.testScripts.Syllabus_BrowseBook" name="TC12_To_Verify_Revision_Is_Disabled_If_Excluded_From_Syllabus" time="28.111">
    <failure message="The following asserts failed:
	User is able to revise chapter which is excluded from syllabus expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
User is able to revise chapter which is excluded from syllabus expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at studi.co.pageModules.Module_Syllabus_BrowseBook.validate_revision_excludeFromSyllabus_functionality(Module_Syllabus_BrowseBook.java:127)
at studi.co.testScripts.Syllabus_BrowseBook.TC12_To_Verify_Revision_Is_Disabled_If_Excluded_From_Syllabus(Syllabus_BrowseBook.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- TC12_To_Verify_Revision_Is_Disabled_If_Excluded_From_Syllabus -->
  <testcase classname="studi.co.testScripts.Syllabus_BrowseBook" name="TC13_To_Verify_Practice_Is_Disabled_If_Excluded_From_Syllabus" time="32.623">
    <failure message="The following asserts failed:
	User is able to start practice which is excluded from syllabus expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
User is able to start practice which is excluded from syllabus expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at studi.co.pageModules.Module_Syllabus_BrowseBook.validate_practice_excludeFromSyllabus_functionality(Module_Syllabus_BrowseBook.java:153)
at studi.co.testScripts.Syllabus_BrowseBook.TC13_To_Verify_Practice_Is_Disabled_If_Excluded_From_Syllabus(Syllabus_BrowseBook.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- TC13_To_Verify_Practice_Is_Disabled_If_Excluded_From_Syllabus -->
  <testcase classname="studi.co.testScripts.Syllabus_BrowseBook" name="TC09_To_Verify_Only_Single_Radio_Button_Can_Be_Select_At_Time" time="21.100">
    <failure message="The following asserts failed:
	Both radio buttons can be select at a time expected [true] but found [false],
	Both radio buttons can be select at a time expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Both radio buttons can be select at a time expected [true] but found [false],
Both radio buttons can be select at a time expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at studi.co.pageModules.Module_Syllabus_BrowseBook.validate_radio_buttons(Module_Syllabus_BrowseBook.java:68)
at studi.co.testScripts.Syllabus_BrowseBook.TC09_To_Verify_Only_Single_Radio_Button_Can_Be_Select_At_Time(Syllabus_BrowseBook.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- TC09_To_Verify_Only_Single_Radio_Button_Can_Be_Select_At_Time -->
  <testcase classname="studi.co.testScripts.Syllabus_BrowseBook" name="TC10_To_Verify_Revision_Functionality" time="25.161">
    <error message="androidx.test.uiautomator.StaleObjectException (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;DESKTOP-JHURRHK&#039;, ip: &#039;192.168.0.100&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;11.0.9&#039;
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {64bit: false, acceptSslCert: false, acceptSslCerts: false, adbExecTimeout: 120000, appActivity: com.tce.view.ui.activities...., appPackage: com.tce.studi, automationName: uiautomator2, browserstack.appium_version: 1.17.0, browserstack.is_hub_canary: false, browserstack.minOSVersion: 5.0, browserstack.networkLogsOptions: {&quot;captureContent&quot;=&gt;true}, buildName: Java Android, bundleID: com.tce.studi, bundleId: com.tce.studi, chromeOptions: {w3c: false}, chromedriverPort: 18084, chromedriverPorts: [[18144, 18154]], databaseEnabled: false, detected_language: selenium/3.141.59 (java win..., device: oneplus 8, deviceApiLevel: 29, deviceManufacturer: OnePlus, deviceModel: IN2011, deviceName: b1c21cce, deviceScreenDensity: 420, deviceScreenSize: 1080x2400, deviceUDID: b1c21cce, enablePerformanceLogging: false, javascriptEnabled: true, locationContextEnabled: false, mobile: {browser: mobile, version: OnePlus 8-10.0}, nativeWebScreenshot: true, networkConnectionEnabled: true, newCommandTimeout: 0, new_bucketing: true, noReset: true, orig_os: android, osVersion: 10.0, os_version: 10.0, pixelRatio: 2.625, platform: ANDROID, platformName: Android, platformVersion: 10, projectName: Tata Studi, realMobile: true, sessionName: Tata Studi, skipServerInstallation: true, statBarHeight: 104, systemPort: 8204, takesScreenshot: true, udid: b1c21cce, uiautomator2ServerLaunchTimeout: 60000, version: , viewportRect: {height: 2067, left: 0, top: 104, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: d2d4e82335e2c7a35150a5fbb4d213c5c0691adf" type="org.openqa.selenium.StaleElementReferenceException">
      <![CDATA[org.openqa.selenium.StaleElementReferenceException: androidx.test.uiautomator.StaleObjectException (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-JHURRHK', ip: '192.168.0.100', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.9'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {64bit: false, acceptSslCert: false, acceptSslCerts: false, adbExecTimeout: 120000, appActivity: com.tce.view.ui.activities...., appPackage: com.tce.studi, automationName: uiautomator2, browserstack.appium_version: 1.17.0, browserstack.is_hub_canary: false, browserstack.minOSVersion: 5.0, browserstack.networkLogsOptions: {"captureContent"=>true}, buildName: Java Android, bundleID: com.tce.studi, bundleId: com.tce.studi, chromeOptions: {w3c: false}, chromedriverPort: 18084, chromedriverPorts: [[18144, 18154]], databaseEnabled: false, detected_language: selenium/3.141.59 (java win..., device: oneplus 8, deviceApiLevel: 29, deviceManufacturer: OnePlus, deviceModel: IN2011, deviceName: b1c21cce, deviceScreenDensity: 420, deviceScreenSize: 1080x2400, deviceUDID: b1c21cce, enablePerformanceLogging: false, javascriptEnabled: true, locationContextEnabled: false, mobile: {browser: mobile, version: OnePlus 8-10.0}, nativeWebScreenshot: true, networkConnectionEnabled: true, newCommandTimeout: 0, new_bucketing: true, noReset: true, orig_os: android, osVersion: 10.0, os_version: 10.0, pixelRatio: 2.625, platform: ANDROID, platformName: Android, platformVersion: 10, projectName: Tata Studi, realMobile: true, sessionName: Tata Studi, skipServerInstallation: true, statBarHeight: 104, systemPort: 8204, takesScreenshot: true, udid: b1c21cce, uiautomator2ServerLaunchTimeout: 60000, version: , viewportRect: {height: 2067, left: 0, top: 104, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: d2d4e82335e2c7a35150a5fbb4d213c5c0691adf
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:45)
at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
at io.appium.java_client.android.AndroidElement.execute(AndroidElement.java:1)
at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:326)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at io.appium.java_client.pagefactory.ElementInterceptor.getObject(ElementInterceptor.java:40)
at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:60)
at io.appium.java_client.android.AndroidElement$$EnhancerByCGLIB$$b598166c.isDisplayed(<generated>)
at studi.co.pageModules.Module_Syllabus_BrowseBook.validate_revision_functionality(Module_Syllabus_BrowseBook.java:79)
at studi.co.testScripts.Syllabus_BrowseBook.TC10_To_Verify_Revision_Functionality(Syllabus_BrowseBook.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- TC10_To_Verify_Revision_Functionality -->
  <testcase classname="studi.co.testScripts.Syllabus_BrowseBook" name="TC11_To_Verify_Practice_Functionality" time="26.208"/>
  <testcase classname="studi.co.testScripts.Syllabus_BrowseBook" name="TC14_To_Verify_Revision_Is_Disabled_If_Completed_In_School" time="30.907">
    <failure message="The following asserts failed:
	User is able to revise chapter which is Completed In School expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
User is able to revise chapter which is Completed In School expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at studi.co.pageModules.Module_Syllabus_BrowseBook.validate_revision_completedInSchool_functionality(Module_Syllabus_BrowseBook.java:180)
at studi.co.testScripts.Syllabus_BrowseBook.TC14_To_Verify_Revision_Is_Disabled_If_Completed_In_School(Syllabus_BrowseBook.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- TC14_To_Verify_Revision_Is_Disabled_If_Completed_In_School -->
</testsuite> <!-- studi.co.testScripts.Syllabus_BrowseBook -->
